data:
  train_csv: "dataset/train_visualCheXbert.csv"
  valid_csv: "dataset/CheXpert-v1.0/valid.csv"
  data_path: "dataset/"
  image_size:
    - 320
    - 320
  dataloader_params:
    batch_size: 64
    num_workers: 32
model_config:
  classifier_model: "densenet"
  optimizer_params:
    lr: 0.0001
    betas:
      - 0.9
      - 0.999
trainer_config:
  accelerator: "gpu"
  max_epochs: 20
model_checkpoint_callback_config:
  save_top_k: -1
  every_n_train_steps: 1000
logger_config:
  project: "CheXpert"
