model:
  lr_scheduler:
    class_path: src.model.lr_schedulers.LinearScheduleWithWarmup
    init_args:
      num_warmup_steps: 2000
      num_training_steps: 148000
      last_epoch: -1
      verbose: false