data:
  train_csv: "dataset/train_split.csv"
  valid_csv: "dataset/val_split.csv"
  data_path: "dataset/"
  classes:
    - Atelectasis
    - Cardiomegaly
    - Consolidation
    - Edema
    - Enlarged Cardiomediastinum
    - Lung Opacity
    - Support Devices
    - Pleural Effusion
  image_size:
    - 224
    - 224
  use_augmentation: True
  normalization_coeffs: 
    - 0.5034475922584534
    - 0.2912977337837219
  dataloader_params:
    batch_size: 48
    num_workers: 8
model_config:
  classifier_model: "swin-vit"
  lr_schedule_params:
    warmup_steps: 500
  optimizer_params:
    weight_decay: 0.01
  lr: 0.0001
  patch_size: 4
trainer_config:
  accelerator: "gpu"
  max_steps: 50000
  auto_lr_find: False
  devices: 4
  strategy: "ddp"
model_checkpoint_callback_config:
  save_top_k: -1
  every_n_train_steps: 1000
  save_weights_only: True
logger_config:
  project: "CheXpert"
